apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: kk-ambulance-ufe
spec:   
  module-uri: http://kk-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: kk-ambulance-wl-app
      path: kk-ambulance-wl
      title: Zoznam čakajúcich kk
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: api-uri
          value: /departments
        - name: base-path
          value: /ui/departments
  preload: false
  proxy: true
  hash-suffix: v1alpha1
